### ISSUE TITLE
Add v10 compatibility

### ISSUE THREAD

**Issue by spoonerWeb** [TYPO3GmbH/ext-hubspot-forms#1]
To work with the hubspot form on typo3.org, we need to have it working with TYPO3 v10.

**Comment by tomasnorre** [comment]
Did a scan with the scanner inside TYPO3 10 Install Tool, and I has only one finding that is a false positive. 

So I think it's a matter of updating the dependencies. 

I've made a PR for this. Please correct me if I'm wrong.

**Comment by tomasnorre** [comment]
https://github.com/TYPO3GmbH/ext-hubspot-forms/pull/2/files

**Comment by susannemoog** [comment]
Fixed and tagged as 1.1.0
